// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmrqsG7x84rDBqPOUx8UXq3tyX3W4BYJs',
    appId: '1:1092742556349:web:c69c801e3901a5e84d25d4',
    messagingSenderId: '1092742556349',
    projectId: 'assistant-a203d',
    authDomain: 'assistant-a203d.firebaseapp.com',
    storageBucket: 'assistant-a203d.firebasestorage.app',
    measurementId: 'G-N2PZJMFR2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5JJBtciZ7jzaQi5flGDDMQ0G6dWjFgj8',
    appId: '1:1092742556349:android:944ed2192652f13e4d25d4',
    messagingSenderId: '1092742556349',
    projectId: 'assistant-a203d',
    storageBucket: 'assistant-a203d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvVBvJNd_NhxaeocylRKUU53qCBcTrRgI',
    appId: '1:1092742556349:ios:f93c1734922feeef4d25d4',
    messagingSenderId: '1092742556349',
    projectId: 'assistant-a203d',
    storageBucket: 'assistant-a203d.firebasestorage.app',
    iosBundleId: 'com.example.flutterVa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvVBvJNd_NhxaeocylRKUU53qCBcTrRgI',
    appId: '1:1092742556349:ios:f93c1734922feeef4d25d4',
    messagingSenderId: '1092742556349',
    projectId: 'assistant-a203d',
    storageBucket: 'assistant-a203d.firebasestorage.app',
    iosBundleId: 'com.example.flutterVa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmrqsG7x84rDBqPOUx8UXq3tyX3W4BYJs',
    appId: '1:1092742556349:web:dacf8dd7aa392e114d25d4',
    messagingSenderId: '1092742556349',
    projectId: 'assistant-a203d',
    authDomain: 'assistant-a203d.firebaseapp.com',
    storageBucket: 'assistant-a203d.firebasestorage.app',
    measurementId: 'G-4Y35TGTE4V',
  );
}
